import {mkdir,readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_PATH?pathToFileURL(process.env.PLAYWRIGHT_PATH).href:'playwright');
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:960},acceptDownloads:true});
const page=await context.newPage(),errors=[],requests=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('request',request=>requests.push({url:request.url(),method:request.method(),body:request.postData()}));
await mkdir('.qa',{recursive:true});
const definition=JSON.parse(await readFile('emulators/eden-duo/emulator.json','utf8'));
const payload=definition.entries[0].emulator;
const fixtureCatalog={consoles:[{shortName:'switch',longName:'Nintendo Switch',emulators:[]},{shortName:'other',longName:'Other',emulators:[]}]};
const inputFile=process.env.REAL_INPUTS==='1'?'emuladores.json':
 {name:'emuladores.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixtureCatalog))};
const original=process.env.REAL_INPUTS==='1'?JSON.parse((await readFile('emuladores.json','utf8')).replace(/^\uFEFF/,'')):fixtureCatalog;
try {
 await page.goto('http://127.0.0.1:4173/emuconfig/');
 assert.equal(await page.locator('#workspace').isVisible(),false);
 await page.locator('#file-input').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{no')});
 await page.locator('#file-error').filter({hasText:'Could not parse JSON'}).waitFor();
 assert.equal(await page.locator('#file-input').getAttribute('multiple'),null);
 await page.locator('#file-input').setInputFiles(inputFile);
 await page.locator('#workspace').waitFor();
 await page.locator('#database-list .emulator-row').first().waitFor();
 assert.equal(await page.locator('#database-count').textContent(),'2 emulators');
 assert.equal(await page.locator('#database-list .emulator-row').count(),2);
 if(process.env.REAL_INPUTS==='1'){
  const original=JSON.parse((await readFile('emuladores.json','utf8')).replace(/^\uFEFF/,''));
  assert.equal(Number(await page.locator('#config-count').textContent()),original.consoles.reduce((count,c)=>count+c.emulators.length,0));
 }
 const trigger=page.getByRole('combobox',{name:'Filter by console'});
 await trigger.click();
 await page.locator('#platform-menu [data-value="switch"]').click();
 await trigger.click();
 const bounds=await page.locator('#platform-menu').boundingBox();
 assert.ok(bounds.height<=320 && bounds.y+bounds.height<=960);
 const selected=await page.locator('#platform-menu [aria-selected="true"]').boundingBox();
 assert.ok(selected.y>=bounds.y && selected.y+selected.height<=bounds.y+bounds.height);
 await page.keyboard.press('Home');await page.keyboard.press('Escape');
 assert.equal(await page.locator('.platform-label').textContent(),'Nintendo Switch');
 const databaseRow=page.locator('#database-list [data-emulator-id="EDEN-DUO"]');
 const configRow=page.locator('#config-list [data-emulator-id="EDEN-DUO"]');
 await databaseRow.locator('.info').click();
 assert.equal(await page.locator('#detail-content select, #detail-content input, #detail-content textarea, #detail-content .detail-action').count(),0);
 assert.deepEqual(JSON.parse(await page.locator('#detail-content pre').textContent()),payload);
 assert.equal(await page.locator('#detail-content .detail-description').textContent(),definition.description);
 await page.screenshot({path:'.qa/description-info.png',animations:'disabled'});
 await page.keyboard.press('Escape');
 await context.setOffline(true);
 await databaseRow.locator('.add').click();
 await configRow.waitFor();
 assert.equal(await databaseRow.locator('.added').isDisabled(),true);
 assert.equal(await page.locator('#workspace-status').textContent(),'1 change');
 await context.setOffline(false);
 await configRow.locator('.info').click();
 assert.deepEqual(JSON.parse(await page.locator('#detail-content pre').first().textContent()),payload);
 assert.equal(await page.locator('#detail-content pre').count(),1);
 assert.equal(await page.locator('#detail-content .detail-description').textContent(),definition.description);
 await page.keyboard.press('Escape');
 await page.locator('#nav-changes').click();
 assert.equal(await page.locator('#preview-dialog .diff-block').count(),1);
 await page.keyboard.press('Escape');
 const output=page.waitForEvent('download');
 await page.locator('#download-config').click();
 const download=await output;
 assert.equal(download.suggestedFilename(),'emuladores.json');
 await download.saveAs('.qa/eden-duo-export.json');
 const exported=JSON.parse((await readFile('.qa/eden-duo-export.json','utf8')).replace(/^\uFEFF/,''));
 const expected=structuredClone(original);expected.consoles.find(c=>c.shortName==='switch').emulators.push(payload);
 assert.deepEqual(exported,expected);
 await page.locator('#file-input').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{no')});
 await page.locator('#workspace-error').waitFor();
 assert.equal(await page.locator('#workspace-status').textContent(),'1 change');
 await page.locator('#file-input').setInputFiles(inputFile);
 await page.locator('#cancel-confirm').click();
 assert.equal(await page.locator('#workspace-status').textContent(),'1 change');
 await page.screenshot({path:'.qa/eden-duo-workspace.png'});
 await configRow.locator('.remove').click();
 assert.equal(await configRow.count(),0);
 assert.equal(await page.locator('#workspace-status').textContent(),'No changes');
 await page.locator('#undo').click();await configRow.waitFor();
 await page.locator('#undo').click();
 assert.equal(await configRow.count(),0);
 assert.equal(await page.locator('#workspace-status').textContent(),'No changes');
 await page.locator('#search').fill('no-such-emulator');
 await page.getByText('No matching emulators.',{exact:true}).waitFor();
 await page.locator('#search').fill('');await databaseRow.waitFor();
 await page.locator('#nav-file').click();
 await page.getByRole('button',{name:'View JSON',exact:true}).first().click();
 assert.match(await page.locator('#preview-content pre').textContent(),/"consoles"/);
 await page.keyboard.press('Escape');
 for(const width of [320,390,768,1024]){
  await page.setViewportSize({width,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 }
 await page.setViewportSize({width:390,height:844});
 await trigger.click();
 const mobile=await page.locator('#platform-menu').boundingBox();
 assert.ok(mobile.x>=0&&mobile.x+mobile.width<=390&&mobile.y+mobile.height<=844&&mobile.height<=320);
 await page.locator('#search').click();
 assert.equal(await trigger.getAttribute('aria-expanded'),'false');
 await databaseRow.locator('.info').click();
 for(let i=0;i<8;i++){await page.keyboard.press('Tab');assert.equal(await page.locator('#detail-dialog').evaluate(e=>e.contains(document.activeElement)),true);}
 await page.keyboard.press('Escape');
 assert.equal(await databaseRow.locator('.info').evaluate(e=>e===document.activeElement),true);
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await page.locator('#download-config').evaluate(e=>getComputedStyle(e).animationName),'none');
 await page.reload();assert.equal(await page.locator('#workspace').isVisible(),false);
 const drop=await page.evaluateHandle(()=>{const dt=new DataTransfer();dt.items.add(new File(['{"consoles":[]}'],'emuladores.json',{type:'application/json'}));return dt;});
 await page.locator('#upload-zone').dispatchEvent('drop',{dataTransfer:drop});
 await page.locator('#workspace').waitFor();
 assert.equal(await page.locator('#config-count').textContent(),'0');
 // Complete console entries remain discoverable even with an empty uploaded catalog.
 const joi=JSON.parse(await readFile('emulators/joiplay/emulator.json','utf8'));
 const joiRow=page.locator('#database-list [data-emulator-id="console:joiplay"]');
 await joiRow.waitFor();
 await trigger.click();await page.locator('#platform-menu [data-value="joiplay"]').click();
 await joiRow.locator('.info').click();
 assert.deepEqual(JSON.parse(await page.locator('#detail-content pre').textContent()),joi.entries[0]);
 await page.keyboard.press('Escape');
 await joiRow.locator('.add').click();
 await page.locator('#config-list [data-emulator-id="JOIPLAY"]').waitFor();
 assert.equal(await joiRow.locator('.added').isDisabled(),true);
 await page.locator('#nav-changes').click();
 assert.deepEqual(JSON.parse(await page.locator('#preview-dialog .diff-block pre').last().textContent()),joi.entries[0]);
 await page.keyboard.press('Escape');
 const joiOutput=page.waitForEvent('download');await page.locator('#download-config').click();
 await (await joiOutput).saveAs('.qa/joiplay-export.json');
 assert.deepEqual(JSON.parse(await readFile('.qa/joiplay-export.json','utf8')),{consoles:joi.entries});
 await page.locator('#undo').click();
 assert.equal(await page.locator('#config-list [data-emulator-id="JOIPLAY"]').count(),0);
 assert.equal(await page.locator('#workspace-status').textContent(),'No changes');
 assert.equal(await joiRow.locator('.add').isEnabled(),true);
 // An existing console with a differently cased short name keeps its metadata.
 const localConsole={shortName:'JOIPLAY',longName:'My games',romExtensions:['.mine'],custom:42,emulators:[]};
 await page.locator('#file-input').setInputFiles({name:'existing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({consoles:[localConsole]}))});
 await joiRow.locator('.add').click();
 const mergedOutput=page.waitForEvent('download');await page.locator('#download-config').click();
 await (await mergedOutput).saveAs('.qa/joiplay-merged.json');
 assert.deepEqual(JSON.parse(await readFile('.qa/joiplay-merged.json','utf8')),{consoles:[{...localConsole,emulators:joi.entries[0].emulators}]});
 await page.locator('#undo').click();
 const customized=structuredClone(joi.entries[0]);customized.emulators[0].commands[0].command='my local command';
 await page.locator('#file-input').setInputFiles({name:'custom.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({consoles:[customized]}))});
 await joiRow.locator('.add').click();await page.locator('#cancel-confirm').click();
 assert.equal(await page.locator('#workspace-status').textContent(),'No changes');
 await joiRow.locator('.add').click();await page.locator('#accept-confirm').click();
 assert.equal(await joiRow.locator('.added').isDisabled(),true);
 await page.locator('#nav-changes').click();await page.getByRole('button',{name:'Undo all',exact:true}).click();
 await page.locator('#accept-confirm').click();
 await page.locator('#preview-dialog').waitFor({state:'hidden'});
 assert.equal(await page.locator('#workspace-status').textContent(),'No changes');
 await page.route('**/eden-duo/emulator.json',route=>route.fulfill({json:{description:'Invalid entry',entries:[]}}));
 await page.reload();await page.locator('#file-input').setInputFiles(inputFile);
 await page.locator('#library-error').waitFor();
 assert.equal(await page.locator('#database-list .emulator-row').count(),1);
 assert.equal(await page.locator('.row-icon, .emulator-row img').count(),0);
 assert.deepEqual(errors,[]);
 assert.ok(requests.every(r=>r.method==='GET'&&!r.body&&r.url.startsWith('http://127.0.0.1:4173/')));
 await writeFile('.qa/eden-duo-results.json',JSON.stringify({passed:true,errors,checks:['custom-only database','exact Eden Duo payload','single-file upload','invalid JSON','platform filter','read-only info','offline add','duplicate detection','exact JSON export','invalid replacement','cancel replacement','remove','undo','search','file preview','mobile','keyboard','reduced motion','refresh clearing','drag/drop','invalid definition handling','no uploads']},null,2));
 console.log('Eden Duo and full console browser checks passed.');
}finally{await browser.close();}

